/*
 * Copyright (c) 2025 Xplat-soft s.r.o.
 *
 * This source code is licensed under the terms found in the
 * LICENSE.md file in the root directory of this source tree
 * or at https://universal-sign-in.com/license
 */
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * Then it was commited to support old arch
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.reactnativegooglesignin;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

// ReactModuleWithSpec is needed for compatibility with RN 0.72. Can be removed in the future.
public abstract class NativeOneTapSignInSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {
  public static final String NAME = "RNOneTapSignIn";

  public NativeOneTapSignInSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void signIn(ReadableMap params, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void signOut(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void revokeAccess(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void explicitSignIn(ReadableMap params, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void checkPlayServices(boolean showErrorResolutionDialog, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void requestAuthorization(ReadableMap params, Promise promise);
}
